### ISSUE TITLE
与 DefaultOptions 不兼容

### ISSUE THREAD

**Issue by al-wei** [Giant-Salted-Fish/Default-Key-Setup#1]
表现为，两边都保存后，重置按键按钮，理想的应该是灰色无法点击状态；但是相反是激活的，点击重置按键按钮后kbp多键变单键的明显变化。

**Comment by Giant-Salted-Fish** [comment]
有这个问题的原因是 DKS 和 Default Options 都依赖 options.txt 是否存在来检查是不是第一次启动游戏，但是 Default Options 会在游戏启动早期自动生成这个文件，而 DKS 的检查是在游戏启动晚期，结果就是 DKS 检测不到游戏是不是第一次启动。v1.0.0.2 更新添加了一个新的 config 选项叫 `force_key_reset`，把它设置成 `true` 就可以强制 DKS 在下次启动游戏的时候重置按键绑定。你可以到 DKS 的[模组发布页](https://www.mcmod.cn/class/17262.html)获取更新。
